import "/public/assets/css/bootstrap.min.css"
import "/public/assets/css/all.min.css"
import "/public/assets/css/magnific-popup.css"
import "/public/assets/css/nice-select.css"
import "/public/assets/css/swiper.min.css"
import "/public/assets/css/aos.css"
import "/public/assets/css/main.css"
import { Plus_Jakarta_Sans } from 'next/font/google'
import localFont from 'next/font/local'

const uber = localFont({
    src: [
        { path: '../public/assets/webfonts/UberMoveMedium.otf', weight: '500', style: 'normal' },
        { path: '../public/assets/webfonts/UberMoveBold.otf', weight: '700', style: 'normal' },
    ],
    variable: "--manrope",
    display: 'swap',
})
const jakarta = Plus_Jakarta_Sans({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: "--jakarta",
    display: 'swap',
})
export const metadata = {
    title: 'MetaZ - Digital Agency',
    description: 'Generated by create next app',
    icons: {
        icon: [
            { url: '/assets/img/logo/favicon.png', type: 'image/png', sizes: '32x32' },
            { url: '/assets/img/logo/favicon.png', type: 'image/png', sizes: '16x16' },
        ],
        shortcut: '/assets/img/logo/favicon.png',
        apple: '/assets/img/logo/favicon.png',
    },
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${uber.variable} ${jakarta.variable} position-relative bg2-clr`}>{children}</body>
        </html>
    )
}
